name       : lsyncd
version    : 2.2.2
release    : 2
source     :
    - https://github.com/axkibe/lsyncd/archive/release-2.2.2.tar.gz : 0bdb12f40f1a52ed2d8e6cb47242d296663a42b30f38d2b8efcb66b43129e009
license    : GPL-2.0
component  : system.utils
summary    : Lsyncd (Live Syncing Daemon) synchronizes local directories with remote targets
description: |
    Lsyncd (Live Syncing Daemon) synchronizes local directories with remote targets
builddeps  :
    - pkgconfig(lua-5.3)
rundeps    :
    - rsync
setup      : |
    unset LD_AS_NEEDED
    %cmake .
build      : |
    unset LD_AS_NEEDED
    %make
install    : |
    unset LD_AS_NEEDED
    %make_install
