name       : lsyncd
version    : 2.2.3
release    : 3
source     :
    - https://github.com/axkibe/lsyncd/archive/release-2.2.3.tar.gz : 7bcd0f4ae126040bb078c482ff856c87e61c22472c23fa3071798dcb1dc388dd
license    : GPL-2.0
component  : system.utils
summary    : Lsyncd (Live Syncing Daemon) synchronizes local directories with remote targets
description: |
    Lsyncd (Live Syncing Daemon) synchronizes local directories with remote targets
builddeps  :
    - pkgconfig(lua)
rundeps    :
    - rsync
environment: |
    unset LD_AS_NEEDED
setup      : |
    %patch -p1 < $pkgfiles/0001-fix-non-versioned-lua-not-search-in-cmake.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install
    # Fix man page install path
    install -dm00644 $installdir/usr/share/man/man1
    mv $installdir/usr/man/lsyncd.1 $installdir/usr/share/man/man1/
    rm -rf $installdir/usr/man
