name       : lsyncd
version    : 2.1.6
release    : 1
source     :
    - https://github.com/axkibe/lsyncd/archive/release-2.1.6.tar.gz : 02c241ee71b6abb23a796ac994a414e1229f530c249b838ae72d2ef74ae0f775
license    : GPL-2.0
component  : system.utils
summary    : Lsyncd (Live Syncing Daemon) synchronizes local directories with remote targets
description: |
    Lsyncd (Live Syncing Daemon) synchronizes local directories with remote targets
builddeps  :
    - pkgconfig(lua-5.1)
rundeps    :
    - rsync
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
